# .travis.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

# This is YAML - indentation levels are crucial

language: cpp
compiler: gcc
dist: bionic
os: linux

_anchors:
  before_install_win: &before_install_win
    - choco install python
    # https://travis-ci.community/t/windows-builds-refreshenv-command-not-found/5803/4
    - eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')
    - python -V
    - python -m pip install git+https://github.com/mdavidsaver/ci-core-dumper#egg=ci-core-dumper

  before_install_lin: &before_install_lin
    - sudo python -m pip install git+https://github.com/mdavidsaver/ci-core-dumper#egg=ci-core-dumper

  addons: &addons_native
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gdb
      - cmake
cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local:.ci
    - VV=1
    - _PVXS_ABORT_ON_CRIT=1
    - PVXS_LOG=*=WARN

install:
  - python .ci/cue.py prepare
  - python .ci/cue.py exec python .ci-local/libevent.py

script:
  - ulimit -c unlimited
  - python .ci/cue.py build
  - python .ci/cue.py --add-path "{TOP}\bundle\usr\{EPICS_HOST_ARCH}\lib" test
  - python .ci/cue.py test-results
  - ./.ci-local/cdt-check.sh

# If you need to do more during install and build,
# add a local directory to your module and do e.g.
#  - ./.ci-local/travis/install-extras.sh

# Define build jobs

# Well-known variables to use
# SET      source setup file
# EXTRA    content will be added to make command line
# STATIC   set to YES for static build (default: NO)
# TEST     set to NO to skip running the tests (default: YES)
# VV       set to make build scripts verbose (default: unset)

# Usually from setup files, but may be specified or overridden
#  on a job line
# MODULES  list of dependency modules
# BASE     branch or release tag name of the EPICS Base to use
# <MODULE> branch or release tag for a specific module
# ...      see README for setup file syntax description

jobs:
  include:

# Windows builds

  - env: BASE=7.0
    os: windows
    compiler: vs2017
    before_install: *before_install_win

  - env: BASE=7.0
    os: windows
    before_install: *before_install_win

# Different configurations of default gcc and clang

  - env: BASE=7.0 LIBEVENT_TAG=release-2.1.11-stable
    addons: *addons_native
    before_install: *before_install_lin

  - env: BASE=3.15
    addons: *addons_native
    before_install: *before_install_lin

  - env: BASE=3.14
    addons: *addons_native
    before_install: *before_install_lin

  - env: BASE=7.0
    compiler: clang
    addons: *addons_native
    before_install: *before_install_lin

# Cross-compilations to Windows using MinGW and WINE
    
  - env: BASE=7.0 WINE=64 TEST=NO BCFG=static
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gdb
        - cmake
        - g++-mingw-w64-x86-64
    before_install: *before_install_lin

  - env: BASE=7.0 WINE=64 TEST=NO
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gdb
        - cmake
        - g++-mingw-w64-x86-64
    before_install: *before_install_lin

# Other gcc versions (added as an extra package)

  - env: BASE=7.0 LIBEVENT_TAG=origin/patches-2.0 LIBEVENT_USE_CMAKE=NO
    dist: trusty
    compiler: gcc-4.8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gdb
        - cmake
        - clang
        - g++-4.8
    before_install: *before_install_lin

  - env: BASE=7.0 LIBEVENT_USE_CMAKE=NO
    dist: trusty
    compiler: gcc-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gdb
        - cmake
        - clang
        - g++-4.9
    before_install: *before_install_lin

  - env: BASE=7.0
    compiler: gcc-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gdb
        - cmake
        - clang
        - g++-6
    before_install: *before_install_lin

  - env: BASE=7.0
    compiler: gcc-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gdb
        - cmake
        - clang
        - g++-7
    before_install: *before_install_lin

  - env: BASE=7.0
    compiler: gcc-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gdb
        - cmake
        - clang
        - g++-8
    before_install: *before_install_lin

# MacOS build

  - env: BASE=7.0
    os: osx
    compiler: clang
    addons: { homebrew: { packages: ["re2c"], update: true } }
    before_install: *before_install_lin
